config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users
  patch 'moodboards/:id', to: 'moodboards#addvote'

  resources :moodboards do
    resources :shoes, only: [:new, :index, :show, :edit, :create, :destroy, :update]
    resources :comments, only: [:new, :create, :destroy]
    resources :moodboard_attachments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :moodboard

  validates :user_id, presence: true
  validates :moodboard_id, presence: true
  validates :comment, presence: true
end

app/models/moodboard.rb
class Moodboard < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :moodboard_attachments
  accepts_nested_attributes_for :moodboard_attachments
  acts_as_taggable_on :tags

  validates :shoe_type, presence: true
  validates :is_finished, inclusion: { in: [true, false] }
  validates :votes, numericality: { only_integer: true, allow_nil: true }
  validates :detail, presence: true
  validates :title, presence: true
end

app/models/moodboard_attachment.rb
class MoodboardAttachment < ApplicationRecord
  belongs_to :moodboard
  mount_uploader :image, ImageUploader
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :moodboard
  belongs_to :user
  mount_uploader :image, ShoePhotoUploader

  validates :votes, numericality: { only_integer: true, allow_nil: true }
  # validates :detail, presence: true
  validates :moodboard, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :moodboards
  has_many :shoes
  has_many :comments
  mount_uploader :prof_pic, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    # NEED TO ADD BIO AND PORTFOLIO FOR DESIGNERS LATER
    devise_parameter_sanitizer.permit(:sign_up, keys: [:prof_pic, :name, :portfolio, :is_designer])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:prof_pic, :is_designer, :portfolio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @moodboard = Moodboard.find(params[:moodboard_id])
    @user = current_user
  end

  def create
    @comment = Comment.new(comments_params)
    @comment.save
    redirect_to moodboard_path(@comment.moodboard)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to moodboard_path(@comment.moodboard)
  end

  private
  def comments_params
    params.require(:comment).permit(:user_id, :moodboard_id, :votes, :comment)
  end
end

app/controllers/moodboard_attachments_controller.rb
class MoodboardAttachmentsController < ApplicationController
  before_action :set_moodboard_attachment, only: [:show, :edit, :update, :destroy]

  # GET /moodboard_attachments
  # GET /moodboard_attachments.json
  def index
    @moodboard_attachments = MoodboardAttachment.all
  end

  # GET /moodboard_attachments/1
  # GET /moodboard_attachments/1.json
  def show
  end

  # GET /moodboard_attachments/new
  def new
    @moodboard_attachment = MoodboardAttachment.new
  end

  # POST /moodboard_attachments
  # POST /moodboard_attachments.json
  def create
    @moodboard_attachment = MoodboardAttachment.new(moodboard_attachment_params)
  end

  # PATCH/PUT /moodboard_attachments/1
  # PATCH/PUT /moodboard_attachments/1.json


  # DELETE /moodboard_attachments/1
  # DELETE /moodboard_attachments/1.json
  def destroy
    @moodboard_attachment.destroy
    respond_to do |format|
      format.html { redirect_to moodboard_attachments_url, notice: 'Moodboard attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moodboard_attachment
      @moodboard_attachment = MoodboardAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moodboard_attachment_params
      params.require(:moodboard_attachment).permit(:moodboard_id, :image)
    end
end

app/controllers/moodboards_controller.rb
class MoodboardsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_moodboard, only: [:show, :edit, :addvote, :destroy]

  def index
    if params[:tag].present?
      @moodboards = Moodboard.tagged_with(params[:tag])
    else
      @moodboards = Moodboard.order(votes: :desc)
    end
  end

  def show
    @comments = Comment.where(moodboard_id: params[:id])
    @moodboard_attachments = @moodboard.moodboard_attachments.all
    @shoes = Shoe.where(moodboard_id: params[:id])
  end

  def new
    @moodboard = Moodboard.new
    @moodboard_attachments = @moodboard.moodboard_attachments.build
  end

  def create
    @moodboard = Moodboard.new(moodboards_params)
    @moodboard.user = current_user

    respond_to do |format|
      if @moodboard.save
        params[:moodboard_attachments]['image'].each do |i|
          @moodboard_attachment = @moodboard.moodboard_attachments.create!(:image => i,
            :moodboard_id => @moodboard.id)
        end
        format.html { redirect_to @moodboard, notice: 'Moodboard was successfully created.'}
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
  end

  def addvote
    @moodboard.increment(:votes, 1)
    @moodboard.save
  end

  def update
  end

  def destroy
    @moodboard.destroy
  end

private

  def set_moodboard
    @moodboard = Moodboard.find(params[:id])
  end

  def moodboards_params
    params.require(:moodboard).permit(:shoe_type, :is_finished, :detail, :votes, :tag_list, :title, moodboard_attachments_attributes: [:id, :moodboard_id, :image])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: :home
  def home

  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  def new
    @shoe = Shoe.new
    @moodboard = Moodboard.find(params[:moodboard_id])
  end

  def create
    @shoe = Shoe.create(shoes_params)
    @shoe.user = current_user
    @shoe.moodboard = Moodboard.find(params[:moodboard_id])
    respond_to do |format|
      if @shoe.save
        format.html { redirect_to moodboard_path(params[:moodboard_id]), notice: 'Shoe successfully uploaded.'}
      else
        format.html { render action: 'new' }
      end
    end
  end

  def index
    @shoes = Shoe.where(moodboard_id: params[:moodboard_id])
  end

  private

  def shoes_params
    params.require(:shoe).permit(:user_id, :moodboard_id, :votes, :image, :detail, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<!-- navbar -->
<%= render "devise/shared/navbar" %>

<!-- form -->
<div class="user-form-wrapper">
  <h1>Add Comment</h1>
  <div class="user-form-container">
      <%= simple_form_for [@moodboard, @comment] do |f| %>
        <%= f.input :comment, { maxlength: 1000 } %>
        <%= f.input :moodboard_id, as: :hidden, input_html: { value: @moodboard.id} %>
        <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id} %>
        <%= f.submit "Share!", class: "btn" %>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>👟 OSSICLE 👟</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>

    <% if notice %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
  <% end %>

    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
 </html>

app/views/moodboard_attachments/new.html.erb
<h1>New Moodboard Attachment</h1>

<%= render 'form', moodboard_attachment: @moodboard_attachment %>

<%= link_to 'Back', moodboard_attachments_path %>

app/views/moodboard_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Moodboard:</strong>
  <%= @moodboard_attachment.moodboard %>
</p>

<p>
  <strong>Image:</strong>
  <%= @moodboard_attachment.image %>
</p>

<%= link_to 'Edit', edit_moodboard_attachment_path(@moodboard_attachment) %> |
<%= link_to 'Back', moodboard_attachments_path %>

app/views/moodboards/index.html.erb
<!-- nav bar -->
<%= render "devise/shared/navbar" %>
<!-- top banner -->
<head>
  <script src="https://unpkg.com/scrollreveal"></script>
</head>

  <div class="inside-banner">
    <h1>Moodboards</h1>

  </div>
<!-- add mood -->

<!-- tags -->
<%= link_to "Add Mood", new_moodboard_path, class: "btn-shoes-pop-up"  %>
<!-- tags header -->
<% if params[:tag].present? %>
  <center><h1><%= params[:tag] %></h1></center>
<% end %>

<!-- cards area -->

<div class="masonry mx-auto text-center">
  <div class="row mx-auto justify-content-center">

      <% @moodboards.each do |moodboard| %>
        <div class="shoes-cards" >
          <script type="text/javascript">
            ScrollReveal().reveal('.shoes-cards', { delay: 150, reset: true });
          </script>
          <div class="card-img-top">
            <% if moodboard.moodboard_attachments.first.nil?  %>
              <h3>Uh oh picture is not loading</h3>
            <% else %>
              <%= cl_image_tag moodboard.moodboard_attachments.first.image, :gravity=>"north_west", :crop => "lfill", class: "cloudimg" %>
            <% end %>
           </div>

          <div class="card-body">
            <h5 class="card-title"><%= moodboard.title %></h5>
            <p class="card-text"><%= moodboard.shoe_type %></p>
          </div>

          <div id="tags">
            <% if moodboard.tag_list.present? %>
              <% moodboard.tag_list.each do |tag| %>
               <div id="each-tag"> <%= link_to tag, moodboards_path(tag: tag) %> </div>
              <% end %>
            <% end %>
           </div>

          <div class="card-footer">
            <ul class="social">
              <li><%= link_to moodboard_path(moodboard.id), method: :patch do %>
                <i class="far fa-heart like-review"  data-id=<%= moodboard.id %>></i>
                <% end %>
              </li>
              <li id="votes_number" data-id=<%= moodboard.id %>> <%= moodboard.votes %></li>
            </ul>
            <div class="btn-shoes-cards">
              <%= link_to "Moods", moodboard_path(moodboard.id) %>
            </div>
          </div>

        </div>
      <% end %>

<!-- Like Button functions -->


  <script type="text/javascript">

    // Variable Declarations
    let votes = document.querySelectorAll('#votes_number')
    let buttons = document.querySelectorAll('.far')

    // Custom Functions
    const like = () => {
      buttons.forEach((button) => {
        button.addEventListener('click', (e) => {
          let buttonId = e.target.dataset.id
          votes.forEach((vote) => {
            if (vote.dataset.id === buttonId) {
              vote.innerText = Number.parseInt(vote.innerText) + 1
               button.classList.add('red-heart')
               button.addAttribute("disabled");
            }
          }, {once : true});
        })
      })
    };

    // Run Functions
    like();
    // like animation
  </script>


  </div>
</div>
  <%= render "devise/shared/footer" %>

app/views/moodboards/new.html.erb
<!-- nav bar -->
<%= render "devise/shared/navbar" %>

<div>
  <div class="inside-banner" style="background-image:url('https://cdn.dribbble.com/users/146798/screenshots/4085472/dribbble.gif')">
    <h1>New Moodboard</h1>
  </div>
</div>

<!-- moodboard form -->

<div class="user-form-wrapper">
  <h1>Enter Details</h1>
  <div class="user-form-container">
    <%= simple_form_for @moodboard, html: { multipart: true } do |f| %>
      <%= f.input :title, { maxlength: 100 }%>
      <%= f.input :detail, { maxlength: 500 } %>
      <%= f.input :shoe_type, { maxlength: 25 } %>
      <%= f.input :tag_list %>
      <%= f.fields_for :moodboard_attachments do |m| %>
        <div class="file-upload">
          <%= m.label :image %>
          <div class="file-btn">
            <%= m.file_field :image, :multiple => true, name: "moodboard_attachments[image][]" %>
          </div>
        </div>
      <% end %>
      <p>
        <%= f.submit "Share!", class: "btn" %>
      </p>
    <% end %>
  </div>
</div>

  <%= render "devise/shared/footer" %>

    <!-- upload area -->

  <!--
  <div class="demo-droppable">
    <p>Drag files here or click to upload</p>
  <input type="file" multiple="true" style="display: none;"></div>
  <div class="output"></div>
  <script type="text/javascript">
    (function(window) {
      function triggerCallback(e, callback) {
        if(!callback || typeof callback !== 'function') {
          return;
        }
        var files;
        if(e.dataTransfer) {
          files = e.dataTransfer.files;
        } else if(e.target) {
          files = e.target.files;
        }
        callback.call(null, files);
      }
      function makeDroppable(ele, callback) {
        var input = document.createElement('input');
        input.setAttribute('type', 'file');
        input.setAttribute('multiple', true);
        input.style.display = 'none';
        input.addEventListener('change', function(e) {
          triggerCallback(e, callback);
        });
        ele.appendChild(input);
        ele.addEventListener('dragover', function(e) {
          e.preventDefault();
          e.stopPropagation();
          ele.classList.add('dragover');
        });
        ele.addEventListener('dragleave', function(e) {
          e.preventDefault();
          e.stopPropagation();
          ele.classList.remove('dragover');
        });
        ele.addEventListener('drop', function(e) {
          e.preventDefault();
          e.stopPropagation();
          ele.classList.remove('dragover');
          triggerCallback(e, callback);
        });
        ele.addEventListener('click', function() {
          input.value = null;
          input.click();
        });
      }
      window.makeDroppable = makeDroppable;
    })(this);
    (function(window) {
      makeDroppable(window.document.querySelector('.demo-droppable'), function(files) {
        console.log(files);
        var output = document.querySelector('.output');
        output.innerHTML = '';
        for(var i=0; i<files.length; i++) {
          if(files[i].type.indexOf('image/') === 0) {
            output.innerHTML += '<img width="200" src="' + URL.createObjectURL(files[i]) + '" />';
          }
          output.innerHTML += '<p>'+files[i].name+'</p>';
        }
      });
    })(this);
  </script>
</div>

app/views/moodboards/show.html.erb
<!-- nav bar -->
<%= render "devise/shared/navbar" %>
<body>

<div class="text_container">
  <div class="bg-text">MOODBOARD</div>
    <div>
     <span class="title-box banner"> <h1><%= @moodboard.title %></h1></span><br>
     <span class="attributes"> <p>👥<br><strong><%= @moodboard.user.name %></strong></p></span>
     <span class="likes"> <p>❤️<br><strong><%= @moodboard.votes %></p></strong></span>
     <span class="attributes"> <p>👟<br><strong><%= @moodboard.shoe_type %></p></strong></span> <br>
    </div>

    <div>
     <span class="description-box">
      <p><strong>Inspiration  <br> </strong> <%= @moodboard.detail %></p>
      <% if @moodboard.tag_list.present? %>
        <p id="tags"><% @moodboard.tag_list.each do |tag| %>
            <%= link_to tag, moodboards_path(tag: tag) %>
          <% end %></p>
      <% end %>
     </span>
    </div>
  </div>
</div>

 <div>
    <% @moodboard_attachments.each do |attachment| %>
      <div class="parallax bg-image" style="background-image: url('<%= cl_image_path attachment.image %>')"></div>
    <% end %>
  </div>

  <div class="popup-banner">
    <div id="check-shoes">
      <h2 style="text-align: center">SHOES<br><br> 👟🎨</h2> <br>
      <!-- <div class="box"> -->
        <div class="btn-line">
          <div> <a class="form-btn" href="#popup1">See Shoes</a></div>
      <!-- </div> -->
         <div><%= link_to "Design Shoes", new_moodboard_shoe_path(@moodboard.id), class: "form-btn"  %></div>
        </div>

      <div id="popup1" class="overlay w-100">
        <!-- ========================================================CAROUSEL TEST -->
        <div class="popup w-100">
          <h2>SHOES DESIGNS</h2>
          <a class="close" href="#">&times;</a>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>

          <div class="carousel-inner w-100">
            <% @shoes.each do |shoe| %>
              <div class="carousel-item active w-100">
                <div class="display-flex">
            <div class="carousel-item">
                <div class="flex">

                  <%= shoe.user.name %>
                  <% if shoe.user.prof_pic.nil?  %>
                    <%= image_tag "http://cf.ltkcdn.net/socialnetworking/images/std/168646-425x425-Cat-Avatar-Primary.jpg", class: "avatar" %>
                  <% else %>
                    <%= cl_image_tag shoe.user.prof_pic.filename, class: "avatar" %>
                  <% end %>

                </div>
                <h3><%= shoe.title %></h3>
                <%= cl_image_tag shoe.image, class: "w-100" %>
                <p><%= shoe.detail %></p>
              </div>
            <% end %>
          </div>

          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <script type="text/javascript">
          const change = () => {
            let active = document.querySelectorAll(".carousel-item")
            active.forEach((item => {
              item.classList.add("active");
              console.log(item)
              item.previousSibling.classList.remove("active")
            }));
          };
          change();
        </script>
       <!-- ========================================================CAROUSEL TEST -->

        <!-- <div class="popup">
          <h2>NEW SHOES</h2>
          <a class="close" href="#">&times;</a>
          <div class="content">
            <img style="max-width:100%"src="https://cdn.dribbble.com/users/458522/screenshots/6157567/snickers_set_no.1.jpg" alt="Shoes"> -->
          </div>
        </div>
      </div>
    </div>
  </div>

<!-- comment box -->
  <div class="comments-banner">
    <h3>Comments box</h3>
    <%= link_to "+ Add Comment", new_moodboard_comment_path(@moodboard) %> <br>
    <div class="comments-box">
          <% if @comments.empty? %>
          <% else %>
            <% @comments.each do |comment| %>
            <div class="comments-lines">
              <img src="https://www.recruitguelph.ca/cecs/sites/uoguelph.ca.cecs/files/public/images/what%27s-your-profile_1.jpg" alt="" style="border-radius:100%;width:40px;height:40px; ">
              <h4><%= comment.user.name %></h4> <br>
              <p><%= comment.comment %></p>
            </div>
            <% end %>
          <% end %>
    </div>
  </div>
</body>
<%= render "devise/shared/footer" %>

app/views/pages/home.html.erb
<!-- nav bar -->

<!-- top banner -->
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.dribbble.com/users/1601802/screenshots/6455062/tike_4.gif);">
    <%= render "devise/shared/navbar" %>
      <div class="container">
        <h1>Ossicle</h1> <br><br>
        <p>Share Your Moodboard <br>Get Your Design</p>
      <div id="banner-card">
        <%= link_to "Go to Moodboards", moodboards_path, class:"btn artist-card" %>
      </div>
      <div class="scroll-down">
        <a class="btn btn-ghost" href="#section2">Scroll down <br> ▽</a>
      </div>
    </div>
  </div>

<!-- separator -->
  <div class="shoes-banner" id="section2">
    <div>
      <h1 class="shoes-banner-title">The Top Designs</h1>
    </div>
  <div>

<!-- design flash cards -->
  <ul id="slider">

    <li>
      <img src="https://cdn.dribbble.com/users/1755078/screenshots/6530828/__19_2x_4x.png" alt="picture" />
      <h2>Adidas Cool</h2>
      <p>Our project just started... <a href="http://flickr.com/photos/justbcuz/112479862/"><br>check it</a></p>
    </li>

    <li>
      <img src="https://cdn.dribbble.com/users/722193/screenshots/3823426/patika.png" alt="picture" />
      <h2>Vans Pride</h2>
      <p>This is life... <a href="http://flickr.com/photos/joshuacraig/2698975899/"><br> check it</a></p>
    </li>

    <li>
      <img src="https://cdn.dribbble.com/users/3460/screenshots/1585477/dropkicks.png" alt="picture" />
      <h2>Adidas Boost</h2>
      <p>Boost with style... <a href="http://flickr.com/photos/ruudvanleeuwen/468309897/"><br>check it</a></p>
    </li>

    <li>
      <img src="https://cdn.dribbble.com/users/180906/screenshots/4824215/screen_shot_2018-07-13_at_4.05.03_pm.png" alt="picture" />
      <h2>New Balance</h2>
      <p>A good idea is balanced... <a href="http://flickr.com/photos/emikohime/294092478/"><br>check it</a></p>
    </li>

    <li>
      <img src="https://cdn.dribbble.com/users/1651856/screenshots/3432820/converse_final.png" alt="picture" />
      <h2>Oasics basic</h2>
      <p>I wanted to show colors in...<a href="http://www.flickr.com/photos/fensterbme/499006584/"><br>check it</a></p>
    </li>

    <li>
      <img src="https://cdn.dribbble.com/users/1084817/screenshots/3144166/yeezyv2_dribbble.jpg" alt="picture" />
      <h2>Reebok White</h2>
      <p>The white its a clean board to... <a href="#"><br>check it</a></p>
    </li>

    <li>
      <img src="https://cdn.dribbble.com/users/1084817/screenshots/3144144/adidas_dribbble.jpg" alt="picture" />
      <h2>Nike Air Max</h2>
       <p>Just do art... <a href="#"><br>check it</a></p>
    </li>

  </ul>

  </div>

<!-- view more button -->
  <div>
    <%= link_to "View More", moodboards_path, class:"btn btn-shoes-banner" %>
  </div>

</div>

<!-- footer -->



</body>
<%= render "devise/shared/footer" %>

app/views/shoes/edit.html.erb
<!-- nav bar -->
<%= render "devise/shared/navbar" %>

<h1>Shoes#edit</h1>
<p>Find me in app/views/shoes/edit.html.erb</p>

app/views/shoes/index.html.erb
<!-- nav bar -->
<%= render "devise/shared/navbar" %>

  <div class="inside-banner mx-auto justify-content-center" >
    <h1>Sneaker Project</h1>
  </div>

  <div class="row mx-auto justify-content-center">
      <% @shoes.each do |shoe| %>

        <div class="shoes-cards" style="width: 20rem;">
          <div class="card-img-top">
            <img src="" alt="">
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= shoe.shoe_type %></h5>
            <p class="card-text">Ipsum Lorem</p>
            <div class="btn-shoes-cards">
              <%= link_to "+", shoes_new_path %>
            </div>
          </div>
          <div>
            <ul class="social">
              <li><i class="far fa-thumbs-up"></i></li>
              <li><%= shoe.votes %></li>
              <li></li>
            </ul>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/shoes/new.html.erb
<!-- nav bar -->
<%= render "devise/shared/navbar" %>

<% if current_user.try(:portfolio) %>

  <!-- new shoe form -->
  <div class="user-form-wrapper">
    <h1>Design Your Cool Shoe</h1>
      <div class="user-form-container">
        <%= simple_form_for [@moodboard, @shoe] do |f| %>
          <div class="field">
            <%= f.input :title, { maxlength: 300 }%>
          </div>
          <div class="field">
            <%= f.input :detail, { maxlength: 1000 } %>
          </div>
          <div class="field">
            <%= f.file_field :image, class: "file-btn" %>
          </div>
          <%= f.submit "HIT IT", class: "btn" %>
        <% end %>
      </div>
  </div>


<% else %>
  <!-- NEED TO FIGURE OUT IF THERE'S ANOTHER SIGN IN TO JUST ADD PORTFOLIO -->
  <div style="border-radius: 10px; display: block; text-align: center; padding: 150px 0px; width: 400px; background-color: #ffd700; margin: auto; height: 300px">

    <h1><%= link_to "Add your portfolio to become a designer", edit_user_registration_path %></h1>

  </div>
<% end %>

app/views/shoes/show.html.erb
<!-- nav bar -->
<%= render "devise/shared/navbar" %>

<h1>Shoes#shoe</h1>
<p>Find me in app/views/shoes/shoe.html.erb</p>